### ISSUE TITLE
Handle AWS WebSocket connection and state

### ISSUE THREAD

**Issue by erm** [erm/mangum#1]
The AWS WebSocket connect event contains the information required to build the connection scope, however the function response needs to be returned immediately in order to begin using connections. 

Unless another solution presents itself, I'm thinking the initial connection event information will need to be persisted through DynamoDB, but there are still some challenges with how to allow the application to negotiate the connection and how to manage the ASGI cycle state generally.

https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-overview.html

**Comment by tomchristie** [comment]
I took a bit of a look around this but it wasn’t at all obvious. I’d be up for helping figure out an approach to it when you come back to it. Perhaps a good signal here to start out by focusing on getting the HTTP side nicely mature first?

**Comment by tomchristie** [comment]
Related: https://www.jeremydaly.com/reuse-database-connections-aws-lambda/

**Comment by erm** [comment]
Basic support included, probably some issues and tweaking ahead but gonna go ahead and close this now.
