### ISSUE TITLE
Dynamodb backend converts table_name to lowercase

### ISSUE THREAD

**Issue by koxudaxi** [erm/mangum#114]
@erm 
Our team often use uppercase names for a dynamodb table.
example: `dynamodb://ProjectName.Local.WebSocket`

But, `DynamoDBBackend` use  `urlparse` to obtain `table_name`
https://github.com/erm/mangum/blob/292aff25ca63832b67a31c7a67939e36a82eeb25/mangum/backends/dynamodb.py#L14-L19

A hostname attribute always returns lowercase.
https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlparse

We should change the logic to support some table_name, which includes uppercase.

**Comment by erm** [comment]
@koxudaxi Yep, that makes sense. All of the WebSocket backends were implemented with no more complexity or configuration than was necessary for my initial testing, so this is a welcomed change. Ideally, I want to keep the `dsn` convention and just change the parsing logic to accomodate any legal DynamoDB table name.

Is this something you'd be willing to PR?

**Comment by koxudaxi** [comment]
@erm 
Thank you for your reply.
I will try to create a PR tonight or tomorrow.
