### ISSUE TITLE
Empty WebSockets request is raised exception

### ISSUE THREAD

**Issue by koxudaxi** [erm/mangum#117]
@erm 
If I send empty WebSockets request then, mangum raise an exception.
mangum doesn't expect an empty body.

the version is  `0.9.0`
```
[ERROR] KeyError: 'body'
Traceback (most recent call last):
  File "/var/task/mangum/adapter.py", line 74, in __call__
    response = self.handler(event, context)
  File "/var/task/mangum/adapter.py", line 88, in handler
    response = self.handle_ws(event, context)
  File "/var/task/mangum/adapter.py", line 226, in handle_ws
    {"type": "websocket.receive", "bytes": None, "text": event["body"]}
```

Would you expect the behavior? Or Should we fix code for this case? 
I guesses we have to fix it like this.
```python
{"type": "websocket.receive", "bytes": None, "text": event.get("body", "")}
```

**Comment by erm** [comment]
@koxudaxi Hm, I had assumed that body key would always be included in the message event. We should fix the code for this case, but first how might I reproduce this event?

**Comment by koxudaxi** [comment]
@erm 
I used [wscat](https://github.com/websockets/wscat) testing it
Sorry, I lost the log. I write a way to reproduce the error.
```bash
$ wscat -c wss://yyyy.execute-api.ap-northeast-1.amazonaws.com/local
Connected (press CTRL+C to quit)
> {"data": "abc"}           ##  <-  type enter after write a request 
< {"inputdata": "abc"}   ## <- get a good response
>                                  ##  <-  type enter without other characters
< {"message": "Internal server error", "connectionId":"xxxx=", "requestId":"xxxx="} ##  <-  get an error
```

**Comment by erm** [comment]
@koxudaxi I see, thanks for that. We should resolve this per your suggestion. Happy to review a PR to handle this, otherwise I'll do it myself at some point this week.
