### ISSUE TITLE
Support additional FaaS platforms

### ISSUE THREAD

**Issue by erm** [erm/mangum#2]
After playing around with Azure Functions in an example [here](https://github.com/erm/azure-functions-python-asgi-example), the behaviour of the ASGI adapters is generic enough that it could be rolled into this project somehow. 

A few things to note:

- Python / Linux support is currently in preview
- Only supports Python 3.6

**Comment by tomchristie** [comment]
What FaaS platforms would be on the radar here?

**Comment by erm** [comment]
Good question... 

I'm still digging into non-AWS platforms generally, but any platform that will fit well into the current adapter scheme without requiring platform-specific requirements/integrations (at least at this point).

I took a look into Google's offerings and based on a cursory glance of the docs for Google App Engine's WSGI service library I am not sure if it would feasible to include, but I need to get into it a bit more to be sure. Google Cloud Functions also have potential, but the beta runtime for relies on Flask requests/responses - which could be adapted but my current understanding is limited.

Also if anyone comes across this and has a request to include a particular platform then I'd be inclined to prioritise those.

**Comment by unixorn** [comment]
How about [OpenFaaS](https://github.com/openfaas/faas)? It can run in kubernetes, so it's nicely generic option people can use anywhere they have a cluster.

**Comment by erm** [comment]
@unixorn that definitely looks interesting! PRs are welcome, but I'm happy to dig into it myself when I have time - would you be able to open an issue to for its inclusion specifically with a brief description?

**Comment by erm** [comment]
Closing this off since the conclusion is to include additional FaaS platforms, a separate issue should be opened for the individual platforms.
