### ISSUE TITLE
Good to recommend to others?

### ISSUE THREAD

**Issue by pgjones** [erm/mangum#25]
This looks great, can I recommend it in the Quart docs?

**Comment by erm** [comment]
Thanks! And yes, that would be great. :) 

I've actually begun using Quart specifically (alongside Starlette) in my tests as well.

**Comment by erm** [comment]
Closing, related https://github.com/erm/mangum/issues/17

**Comment by pgjones** [comment]
Done, https://gitlab.com/pgjones/quart/commit/e71989b1a06622fad243ef4a4341a79ff5ba2079
