### ISSUE TITLE
Reconsidering multiple platform support

### ISSUE THREAD

**Issue by erm** [erm/mangum#29]
So initially I set out to implement an adapter for AWS Lambda / API Gateway, but then I was curious and started experimenting with Azure Functions. This led to shifting focus to multiple platform support, but after getting to this point, I'm wondering if this should be reconsidered because:

- Nearly all cases where I've seen interest in serverless ASGI has been for AWS Lambda specifically.

- It may be better to provide great support for a single platform that has widespread use vs. OK support for multiple platforms that don't get used much.

- WebSocket support in AWS is definitely something platform-specific I want to focus on.

- Creating deployment examples is much easier when considering one platform and perhaps I can eventually get some decent tooling to make that process as simple as possible here.

If there isn't any strong support to include other platforms, then I think I may re-focus back on solely the AWS case and pull the Azure Functions support into a different project.

Does anyone thoughts on this?

**Comment by erm** [comment]
Went ahead and did it. https://github.com/erm/mangum/pull/30

The Azure Functions are now in https://github.com/erm/bonnette and probably won't get too much attention unless some interest presents itself there.

Going to update third-party docs now.

**Comment by tomchristie** [comment]
Probably a good call. Stay focused. 👍
