### ISSUE TITLE
More code examples

### ISSUE THREAD

**Issue by erm** [erm/mangum#31]
So the examples so far have been relatively basic "Hello World" applications, it would be good to test this against some more complex examples in order to shake out any further fixes/additions to the implementation.

**Comment by mojimi** [comment]
Specifically include example with specific ASGI frameworks! Quart/Sanic/Starlette comes to my mind.

**Comment by erm** [comment]
@mojimi you can find some minimal examples for a few frameworks [here](https://github.com/erm/asgi-examples/tree/master/mangum) - though they haven't been updated for any ASGI3 changes (may need to specify a `spec_version`).

Not sure when I may get around to any further examples, but it will likely coincide with any developments around deployment tooling.

**Comment by erm** [comment]
Closing in favour of https://github.com/erm/mangum/issues/48
