### ISSUE TITLE
Drop 3.6 support

### ISSUE THREAD

**Issue by erm** [erm/mangum#33]
I don't think this project should need to support 3.6 since AWS Lambda supports 3.7. I would have started from this perspective, but initially I included the Azure Functions adapter which only supported 3.6.

**Comment by chgangaraju** [comment]
It would be really helpful if it has 3.6 support unless it's really difficult to maintain. It matters when we are working on different projects and need to use a different python version for one project because of a specific library.

**Comment by erm** [comment]
@chgangaraju I don't think it should be too difficult to maintain and may be open to supporting 3.6 again, what are some example cases?

**Comment by erm** [comment]
I am going to close this again for now, but willing to reconsider if there are examples to support 3.6 again - it is not apparent to me where this would be useful.
