### ISSUE TITLE
Use with serverlessframework

### ISSUE THREAD

**Issue by 1oglop1** [erm/mangum#38]
Hi, is there any chance to use this easily as https://github.com/logandk/serverless-wsgi? 
Thank you

**Comment by erm** [comment]
@1oglop1 possibly. I have been keen to get some configuration/deploy tools in here, but I haven't dedicated a lot of time to pursuing anything beyond the adapter classes at this point. I am definitely open to an approach similar to this.

**Comment by erm** [comment]
I am going to try and provide some custom tools, so any serverless plugin would be better off in a separate project - may be able to assist with anyone else's efforts there but won't be including it here.
