### ISSUE TITLE
Handle Exception on mangum

### ISSUE THREAD

**Issue by koxudaxi** [erm/mangum#60]
Thank you for creating great library!!

I found the not good behavior when calling `exception_handler` with `Exception` on `FastAPI`

I defined `exception_hanlder` for `Exception` which returns `JSONResponse`.
```
@app.exception_handler(Exception)
def all_exception_handler(_: Any, error: Exception):
    return JSONResponse(status_code=500, content={"message": error.args, "code": 500})
```

I want to get a response on which status code is 500 with content.
FastAPI(Starrett) raises `Exception`.
Mangum doesn't handle the exception and lambda was die.  I can't get an excepted response from APIGateway.

However,  `Uvicorn` handles the exception and returns expected response.

Could you change Mangum to return excepted response?
If you need the PR then, I can do it.

Thank you.

**Comment by erm** [comment]
@koxudaxi thanks for bringing this to my attention. I've started working on a solution that I should be able to PR tonight or tomorrow.

**Comment by erm** [comment]
The changes are now merged into the master branch. There are a few other things I want to refactor in the adapter then I'll push a release.

**Comment by koxudaxi** [comment]
I have watched the master branch!!
Thank you very much.
