### ISSUE TITLE
Automatically detect if lifespan is supported

### ISSUE THREAD

**Issue by erm** [erm/mangum#62]

**Comment by erichonkanen** [comment]
Is there any more documentation from aws or here that explains what lifespan is or what enabling it means for the asgi app? Is it to keep the app instance running for the entire lifetime of the lambda container?

**Comment by erm** [comment]
@erichonkanen lifespan in this context refers to an ASGI sub-specification - you can read more about it here: https://asgi.readthedocs.io/en/latest/specs/lifespan.html.

**Comment by erichonkanen** [comment]
@erm ah great, thank you! also thanks for updating the readme :)
