### ISSUE TITLE
Retrieve lambda event object on FastAPI

### ISSUE THREAD

**Issue by koxudaxi** [erm/mangum#64]
I use mangum with FastAPI.
Also, I often create an app which authenticates the request by `Cognito` 

I want to obtain a few `Cognito` information(eg: `cognitoIdentityPoolId `) from lambda `event` because I must use the information for business logic on API.
(https://docs.aws.amazon.com/lambda/latest/dg/with-on-demand-https.html)

Unfortunately, Mangum doesn't pass the raw lambda event object to a function(controller).
Is there a way to retrieve an event object of lambda?
Or, Could you please implement it? 
Btw, I don't know how to pass it to a function 😕

**Comment by erm** [comment]
I'm working on a PR that will include the `event` and `context` objects in the ASGI scope. I'll reference this issue when I push the changes.

**Comment by erm** [comment]
@koxudaxi I've merged the changes into master. Here is an example of how you can access the event and context using FastAPI:

```python
from fastapi import FastAPI
from starlette.requests import Request

app = FastAPI()


@app.get("/")
def hello_world(request: Request):
    return {"aws": request.scope["aws"]}
```

**Comment by koxudaxi** [comment]
Thank you very much!!

**Comment by erichonkanen** [comment]
greetings, just stumbled upon this, definitely would be helpful to have it in the main readme doc on the front page! went to access the apigateway event.requestContext.authorizor data and realized I didn't know how to get it :)

Thanks for the pr!

**Comment by erm** [comment]
@erichonkanen yeah, there is definitely some work needed on the docs. There is an open issue for documentation generally https://github.com/erm/mangum/issues/48. 

I’ll try to get to it at some point, but open to PRs as well. :)

**Comment by iglikoxha** [comment]
It was changed to:
`request.scope["aws.event"]`

Still no documentation about it
