### ISSUE TITLE
Error when no headers in request to API gateway

### ISSUE THREAD

**Issue by SKalt** [erm/mangum#69]
I've got a normal setup, based closely on the example in magnum-cli and terraform docs on AWS lambda.  Using the AWS api gateway test button throws this error:

```yml
# loosely translated from the API gateway log
Endpoint response body before transformations:
  errorMessage:
    message: 'NoneType' object has no attribute 'get'
    errorType: AttributeError
    stackTrace: >
      File "/var/task/mangum/adapter.py", line 40, in __call__
        raise exc
      File "/var/task/mangum/adapter.py", line 35, in __call__
        response = self.handler(event, context)
      File "/var/task/mangum/adapter.py", line 50, in handler
        response = handle_http(self.app, event, context)
      File "/var/task/mangum/protocols/http.py", line 58, in handle_http
        server, client = get_server_and_client(event)
      File "/var/task/mangum/utils.py", line 22, in get_server_and_client
        server_addr = event["headers"].get("Host", None)
```

Adding `Accept:application/json` to the textbox for headers resolves the issue, and I get my expected `{ greeting: "hello" }` JSON back.

**Comment by allan-simon** [comment]
I'm still having this error (with the same workaround of addding the header ) though I'm using 0.7.0

**Comment by erm** [comment]
@allan-simon can you post your full traceback using 0.7.0? I can take a look.

**Comment by allan-simon** [comment]
{"errorMessage": "'NoneType' object has no attribute 'get'", "errorType": "AttributeError", "stackTrace": ["  File "/var/task/mangum/adapter.py", line 60, in __call__
    raise exc
", "  File "/var/task/mangum/adapter.py", line 58, in __call__
    response = self.handler(event, context)
", "  File "/var/task/mangum/adapter.py", line 72, in handler
    response = self.handle_http(event, context)
", "  File "/var/task/mangum/adapter.py", line 84, in handle_http
    server, client = get_server_and_client(event)
", "  File "/var/task/mangum/adapter.py", line 24, in get_server_and_client
    server_addr = event["headers"].get("Host", None)
"]}

**Comment by allan-simon** [comment]
it seems it's only a problem for the first call , and after the second call on api gateway it seems to work without additional headers

**Comment by SKalt** [comment]
[adapter.py line 24](https://github.com/erm/mangum/blob/master/mangum/adapter.py#L24) yep, the index-style dict access could fail there. Proposal: replace all the index-style dict access with `.get(key, with_fallback)`.

**Comment by allan-simon** [comment]
@SKalt  thanks, I've proposed a PR here https://github.com/erm/mangum/pull/84
