### ISSUE TITLE
How to connect with Django app?

### ISSUE THREAD

**Issue by levinotik** [erm/mangum#77]
Hi there, 

I'm trying to get a better idea of what using Mangum usage looks like with a Django application. I've looked at the example, but don't really understand how that translates to pointing to a Django application. 

More specifically, what does `app` in

```
handler = Mangum(app, enable_lifespan=False)
```

refer to when pointing to a full Django application?

**Comment by erm** [comment]
This is something I’d like to document here, but I haven’t had a chance to dig into the latest developments for ASGI support in Django yet.  In regards to Channels, it does [not](https://github.com/django/channels/issues/1319) currently support ASGI 3, so it will not work with Mangum - though I am open to supporting ASGI 2 here again.

**Comment by erm** [comment]
Closing in favour of https://github.com/erm/mangum/issues/48

**Comment by erm** [comment]
@levinotik I've created a Django application example using Serverless Framework if you're still interetsed, can find it here: https://github.com/erm/serverless-mangum-examples/

**Comment by levinotik** [comment]
Will check it out, thanks so much!

**Comment by levinotik** [comment]
@erm Thanks again. I know Websockets are still not supported. Will Django Channels work with Mangum? Looking to be able to use GraphQL subscriptions.

**Comment by erm** [comment]
@levinotik I added an example configuration for Channels to the [docs](https://mangum.io/asgi/#channels). I did just a brief test with the chat app from Channels tutorial, but didn't attempt to integrate any of the WebSockets backend stuff into it. 

You can try with the current state of the master branch and should be able to get something working (could be potential issues I haven't anticipated, but you are able to try now).

**Comment by levinotik** [comment]
Awesome, thanks a lot @erm
