### ISSUE TITLE
Handle non root base path of API Gateway custom domain

### ISSUE THREAD

**Issue by jaehyeon-kim** [erm/mangum#78]
Hi

It fails to map a path correctly if an API is deployed to non root base path (eg /api) of API Gateway custom domain. serverless-wsgi handles it with an environment variable named API_GATEWAY_BASE_PATH - https://github.com/logandk/serverless-wsgi#custom-domain-names. (source - https://github.com/logandk/serverless-wsgi/blob/master/serverless_wsgi.py#L112).

It'll be helpful if the class is updated something similar shown below.

```py
@dataclass
class Mangum:

    app: ASGIApp
    enable_lifespan: bool = True
    api_gateway_base_path: str = None
    log_level: str = "info"

...

    def strip_base_path(self, event: dict):
        path_info = event["path"]
        if self.api_gateway_base_path:
            script_name = "/" + self.api_gateway_base_path
            if path_info.startswith(script_name):
                path_info = path_info[len(script_name) :]
        return urllib.parse.unquote(path_info or "/")

    ....

    def handle_http(self, event: dict, context: dict) -> dict:
        ...
        scope = {
            ...
            "path": self.strip_base_path(event),
            ...
        }
    ...
```

Thanks.

**Comment by erm** [comment]
@jaehyeon-kim thanks for raising this. Would you like to put in PR with your proposed changed? Otherwise I can take a look later.

**Comment by jaehyeon-kim** [comment]
Hi @erm 

Please find this PR - https://github.com/erm/mangum/pull/79.

Cheers,
Jaehyeon

**Comment by erm** [comment]
Resolved by https://github.com/erm/mangum/pull/79
