### ISSUE TITLE
[Feature Request] Support multiValueQueryStringParameters

### ISSUE THREAD

**Issue by koxudaxi** [erm/mangum#80]
API Gateway gives `multiValueQueryStringParameters` to lambda when QueryParameters are multiple parameters. 

However, mangum always passes `queryStringParameters` to `query_string` in ASGI's scope.

I can create a PR if you want it to support multiple query parameters. 

## Related Links
https://aws.amazon.com/blogs/compute/support-for-multi-value-parameters-in-amazon-api-gateway/

**Comment by erm** [comment]
@koxudaxi yep, I think we ought to support this here. Please go ahead and open a PR, thanks!

**Comment by erm** [comment]
Resolved by https://github.com/erm/mangum/pull/81

**Comment by erm** [comment]
Reopening this because I'm noticing that https://github.com/erm/mangum/pull/81 actually replaces `queryStringParameters`, but we should be handling (and testing) both. I'll put forward a PR myself when I have a chance, but happy to accept any additional PRs in the meantime.

**Comment by koxudaxi** [comment]
@erm 
>  we should be handling (and testing) both.

I think we don't need to handle `queryStringParameters`
I tested a lambda app with a single query parameter and multi-value query parameters.
API Gateway always gives `Event` with `queryStringParameters` and `multiValueQueryStringParameters`.
If I'm misunderstood then I'm sorry.
But, we may need to add a test for a single query parameter.

**Comment by koxudaxi** [comment]
@erm 
I put the event results.
 ![screenshot25](https://user-images.githubusercontent.com/630670/71556162-1da4c080-2a78-11ea-9313-1f14b31f06f2.png)

I show you some patterns as text.

1. 
`?test=param1&test=param2`
```
'queryStringParameters': {'test': 'param2'}, 'multiValueQueryStringParameters': {'test': ['param1', 'param2']}, 
```

2. 
`?test=param1`
```
 'queryStringParameters': {'test': 'param1'}, 'multiValueQueryStringParameters': {'test': ['param1']},
```

3.
`?test=`
```
'queryStringParameters': {'test': ''}, 'multiValueQueryStringParameters': {'test': ['']},
```
4.
Query parameter is nothing
```
 'queryStringParameters': None, 'multiValueQueryStringParameters': None, 
```

**Comment by erm** [comment]
@koxudaxi thanks for explaining! I wasn’t aware of how normal query strings would work with the new changes. If you could PR a test to the effect of your examples I would appreciate it.
