### ISSUE TITLE
Missing 'typing_extensions' Dependency in 0.7.2

### ISSUE THREAD

**Issue by Amiram1** [erm/mangum#85]
New version raises a:  ModuleNotFoundError: No module named 'typing_extensions' on python3.7. Fallback to 0.7.0 works fine.

**Comment by burritoIand** [comment]
ah, just left a comment on that LOC, glad I'm not alone :) will revert to 0.7.0 for now

**Comment by erm** [comment]
I changed how the version was referenced in `setup.py`, and it caused an issue when installing. I've pushed a new release 0.7.3 to fix the regression.

**Comment by burritoIand** [comment]
thanks!
