### ISSUE TITLE
Lambda Warmer

### ISSUE THREAD

**Issue by yeyeric** [erm/mangum#91]
Hello,

I'm using fast api and AWS Lambda, and migrated successfully my projects thanks to your plugin, thanks a lot for that.

I'm now trying to add a warmer so that my lambda is called every 5 min.
I've found this https://pypi.org/project/lambda-warmer-py/ and I'm struggling to add the decorator since to work, we don't have any function to call.

How shoud I do to make use of this lambda warmer ?

I've tried to create a function named handler which would return Mangum(app) if 'warmer' not in events but this doesn't work.

A bit lost here how to do so

thanks

**Comment by erm** [comment]
@yeyeric could you post your attempt to create the function? This will give me a better idea of how you are using it.

**Comment by yeyeric** [comment]
Initially, I have:

`handler = Mangum(app)`

I've tried:

@lambdawarmer.warmer
def handler(event, context):
    if event.get('warmer'):
         pass
    else:
         return Mangum(app)


Tried also many crazy combinations like
```
@lambdawarmer.warmer
def z(event, context):
    if event.get('warmer'):
        pass
    else:
        return app

handler = Mangum(z)
```

and of course:
```
@lambdawarmer.warmer
handler = Mangum(app)
```

all of which don't work at all....

**Comment by erm** [comment]
The adapter `Mangum` implements a `__call__()` method that receives the `event` and `context` as arguments, so you want to try something like this:

```python
@lambdawarmer.warmer
def handler(event, context):
    if event.get('warmer'):
        pass

    return Mangum(app)(event, context)
```
alternatively, the following is the same as above (but might make the behaviour more clear):

```python
@lambdawarmer.warmer
def lambda_handler(event, context):
    if event.get('warmer'):
        pass

    asgi_handler = Mangum(app)
    response = asgi_handler(event, context) # Call the instance with the event arguments

    return response
```

**Comment by erm** [comment]
Closing this now, but feel free to comment further if you run into any issues.

**Comment by apptechxonia** [comment]
`if event.get('warmer'):`

Is this 'warmer' name of AWS EventBridge Rule name? My rule name in AWS eventbridge is warmer_test . Do I replace with 
```
@lambdawarmer.warmer(flag='am_i_a_warmer', concurrency= 1, delay=150, send_metric= True)
def handler(event, context):
    
    if event.get('warmer_test'):
        print("inside warmer")
        pass
    asgi_handler = Mangum(app)
    response = asgi_handler(event, context) # Call the instance with the event arguments

    return response
```
When I check Lambda logs in Cloudwatch I dont see "inside warmer" printed. In other cases, print text is found in lambda logs
