### ISSUE TITLE
Mangum incorrectly assumes the response should be base64 encoded if the request is base64 encoded

### ISSUE THREAD

**Issue by lsorber** [erm/mangum#92]
If the Lambda Proxy Integration receives an event that has `isBase64Encoded: true`, then Mangum incorrectly assumes [1] that the output should also be base64 encoded [2].

This makes sense if the Lambda processes e.g., an image into another image. However, if the Lambda takes in an image and returns a JSON, then the JSON will be base64 encoded even though it shouldn't be.

[1] https://github.com/erm/mangum/blob/master/mangum/adapter.py#L120
[2] https://github.com/erm/mangum/blob/master/mangum/protocols/http.py#L96

Related issue: #90

**Comment by lsorber** [comment]
This is how Zappa handles that logic [1]:

```python
if response.data:
    if settings.BINARY_SUPPORT and \
            not response.mimetype.startswith("text/") \
            and response.mimetype != "application/json":
        zappa_returndict['body'] = base64.b64encode(response.data).decode('utf-8')
        zappa_returndict["isBase64Encoded"] = True
    else:
        zappa_returndict['body'] = response.get_data(as_text=True)
```

[1] https://github.com/Miserlou/Zappa/blob/master/zappa/handler.py#L551

**Comment by lsorber** [comment]
Workaround we're using for now:

```python
import mangum.protocols.http

def _monkey_patch_post_init(post_init):
    def _patched_post_init(self):
        self.is_binary = False
        return post_init(self)

    return _patched_post_init

mangum.protocols.http.ASGIHTTPCycle.__post_init__ = _monkey_patch_post_init(mangum.protocols.http.ASGIHTTPCycle.__post_init__)
```

**Comment by erm** [comment]
Thanks for raising this and adding all the details. When I have some time I’ll look at fixing it - also happy to review any PRs.

**Comment by lsorber** [comment]
You're welcome. I wrote a small PR to get the fix started, but unfortunately don't have the capacity to finish the details. Hope it's in the direction of how you would address this bug!

**Comment by erm** [comment]
Closed by https://github.com/erm/mangum/pull/93

**Comment by sses79** [comment]
erm
Could you include this in the new release?  Many thanks
